export const SUBMIT_QUERY = 'SUBMIT_QUERY';
export const PROCESS_QUERY_START = 'PROCESS_QUERY_START';
export const PROCESS_QUERY_SUCCESS = 'PROCESS_QUERY_SUCCESS';
export const PROCESS_QUERY_FAILURE = 'PROCESS_QUERY_FAILURE';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SELECT_HISTORY_ITEM = 'SELECT_HISTORY_ITEM';
export const SUGGEST_QUERIES = 'SUGGEST_QUERIES';